version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: ConsoleApps\FunWithSpikes\FunWithSpikes.sln
  verbosity: minimal
artifacts:
- path: '\ConsoleApps\FunWithSpikes\FunWithSpikes\bin'
  name: Fun With Spikes
deploy:
- provider: GitHub
  tag: AppVeyor-v$(appveyor_build_version)
  auth_token:
    secure: oRw/rxGOqxHGggb5dxOwNJTkzB4tReQYS6d4CFjvNxMyvEAjQXWCWeZ1H5wsAQJThuJWbcgAnLK/+wWWf9hkI1j4BBV3dAjXQrB8U71FBlI=
  artifact: Fun With Spikes
