version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore ConsoleApps\FunWithSpikes\FunWithSpikes.sln
build:
  project: ConsoleApps\FunWithSpikes\FunWithSpikes.sln
  verbosity: minimal
artifacts:
- path: '\ConsoleApps\FunWithSpikes\FunWithSpikes\bin'
  name: Fun With Spikes
deploy:
- provider: GitHub
  tag: AppVeyor-v$(appveyor_build_version)
  auth_token:
    secure: lgX4GxJWzuYLXkho9D//SrnbrvVAhjBP/3X/Jmcg6pXZtToG7E1GwBr7vXGSqNAu
  artifact: /.*\Artifact1.*
- provider: NuGet
  api_key:
    secure: 1kBNjaCsKUKkhgEIMDY4BcaDQrhwrMdWFlyWW2gr7yY/d3O9OmStZFdDOUY61pFo
  artifact: 
